// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UIBACKUP

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_ButtonNewSession = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Main_ButtonNewSession, lv_pct(90));
    lv_obj_set_height(ui_Main_ButtonNewSession, lv_pct(20));
    lv_obj_set_x(ui_Main_ButtonNewSession, lv_pct(0));
    lv_obj_set_y(ui_Main_ButtonNewSession, lv_pct(-15));
    lv_obj_set_align(ui_Main_ButtonNewSession, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_ButtonNewSession, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_ButtonNewSession, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Label2 = lv_label_create(ui_Main_ButtonNewSession);
    lv_obj_set_width(ui_Main_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label2, "NEW");
    lv_obj_set_style_text_font(ui_Main_Label2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_TopPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Main_TopPanel, lv_pct(100));
    lv_obj_set_height(ui_Main_TopPanel, lv_pct(10));
    lv_obj_set_x(ui_Main_TopPanel, lv_pct(0));
    lv_obj_set_y(ui_Main_TopPanel, lv_pct(-45));
    lv_obj_set_align(ui_Main_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Main_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_TopPanelBattery = lv_img_create(ui_Main_TopPanel);
    lv_img_set_src(ui_Main_TopPanelBattery, &ui_img_battery_3_bar_png);
    lv_obj_set_width(ui_Main_TopPanelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_TopPanelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_TopPanelBattery, lv_pct(5));
    lv_obj_set_y(ui_Main_TopPanelBattery, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_TopPanelScan = lv_img_create(ui_Main_TopPanel);
    lv_img_set_src(ui_Main_TopPanelScan, &ui_img_contactless_png);
    lv_obj_set_width(ui_Main_TopPanelScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_TopPanelScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_TopPanelScan, lv_pct(-45));
    lv_obj_set_y(ui_Main_TopPanelScan, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelScan, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelScan,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Main_TopPanelButtonSettings = lv_imgbtn_create(ui_Main_TopPanel);
    lv_imgbtn_set_src(ui_Main_TopPanelButtonSettings, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings_png, NULL);
    lv_imgbtn_set_src(ui_Main_TopPanelButtonSettings, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_settings_png, NULL);
    lv_obj_set_height(ui_Main_TopPanelButtonSettings, 48);
    lv_obj_set_width(ui_Main_TopPanelButtonSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Main_TopPanelButtonSettings, lv_pct(-20));
    lv_obj_set_y(ui_Main_TopPanelButtonSettings, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelButtonSettings, LV_ALIGN_CENTER);

    ui_Main_TopPanelButtonTime = lv_btn_create(ui_Main_TopPanel);
    lv_obj_set_height(ui_Main_TopPanelButtonTime, 48);
    lv_obj_set_width(ui_Main_TopPanelButtonTime, lv_pct(40));
    lv_obj_set_x(ui_Main_TopPanelButtonTime, lv_pct(35));
    lv_obj_set_y(ui_Main_TopPanelButtonTime, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelButtonTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelButtonTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelButtonTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_TopPanelButtonTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_TopPanelButtonTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Main_TopPanelButtonTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Main_TopPanelButtonTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_TopPanelTime = lv_label_create(ui_Main_TopPanelButtonTime);
    lv_obj_set_width(ui_Main_TopPanelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_TopPanelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_TopPanelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_TopPanelTime, "22:59");
    lv_obj_set_style_text_color(ui_Main_TopPanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Main_TopPanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Main_TopPanelTime, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_Label1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Main_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Main_Label1, lv_pct(0));
    lv_obj_set_y(ui_Main_Label1, lv_pct(-32));
    lv_obj_set_align(ui_Main_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label1, "SESSION");
    lv_obj_set_style_text_font(ui_Main_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_ButtonRecentSession = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Main_ButtonRecentSession, lv_pct(90));
    lv_obj_set_height(ui_Main_ButtonRecentSession, lv_pct(20));
    lv_obj_set_x(ui_Main_ButtonRecentSession, lv_pct(0));
    lv_obj_set_y(ui_Main_ButtonRecentSession, lv_pct(8));
    lv_obj_set_align(ui_Main_ButtonRecentSession, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_ButtonRecentSession, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_ButtonRecentSession, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Main_Label4 = lv_label_create(ui_Main_ButtonRecentSession);
    lv_obj_set_width(ui_Main_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Main_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Main_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label4, "CONT...");
    lv_obj_set_style_text_font(ui_Main_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main_RollerRecentSessions = lv_roller_create(ui_Main);
    lv_roller_set_options(ui_Main_RollerRecentSessions, "240803_1\n240805_1\n240823_1\n240823_2\n240823_3",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Main_RollerRecentSessions, 4, LV_ANIM_OFF);
    lv_obj_set_width(ui_Main_RollerRecentSessions, lv_pct(90));
    lv_obj_set_height(ui_Main_RollerRecentSessions, lv_pct(30));
    lv_obj_set_x(ui_Main_RollerRecentSessions, lv_pct(0));
    lv_obj_set_y(ui_Main_RollerRecentSessions, lv_pct(35));
    lv_obj_set_align(ui_Main_RollerRecentSessions, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Main_RollerRecentSessions, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Main_RollerRecentSessions, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Main_ButtonNewSession, ui_event_Main_ButtonNewSession, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_TopPanelScan, ui_event_Main_TopPanelScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_TopPanelButtonSettings, ui_event_Main_TopPanelButtonSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_TopPanelButtonTime, ui_event_Main_TopPanelButtonTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_ButtonRecentSession, ui_event_Main_ButtonRecentSession, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}
