// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project_OTR_UI

#include "../ui.h"

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "I am main screen");

    ui_Status_Bar = lv_obj_create(ui_Main);
    lv_obj_set_height(ui_Status_Bar, 26);
    lv_obj_set_width(ui_Status_Bar, lv_pct(100));
    lv_obj_set_x(ui_Status_Bar, 0);
    lv_obj_set_y(ui_Status_Bar, -147);
    lv_obj_set_align(ui_Status_Bar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Status_Bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RFID = lv_img_create(ui_Status_Bar);
    lv_img_set_src(ui_RFID, &ui_img_contactless_png);
    lv_obj_set_width(ui_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RFID, -46);
    lv_obj_set_y(ui_RFID, 0);
    lv_obj_set_align(ui_RFID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RFID, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RFID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bluetooth = lv_img_create(ui_Status_Bar);
    lv_img_set_src(ui_Bluetooth, &ui_img_bluetooth_png);
    lv_obj_set_width(ui_Bluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Bluetooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Bluetooth, 2);
    lv_obj_set_y(ui_Bluetooth, 0);
    lv_obj_set_align(ui_Bluetooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bluetooth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Bluetooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiAP = lv_img_create(ui_Status_Bar);
    lv_img_set_src(ui_wifiAP, &ui_img_wifi_tethering_png);
    lv_obj_set_width(ui_wifiAP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiAP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiAP, -22);
    lv_obj_set_y(ui_wifiAP, 0);
    lv_obj_set_align(ui_wifiAP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiAP, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifiAP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifi = lv_img_create(ui_Status_Bar);
    lv_img_set_src(ui_wifi, &ui_img_wifi_png);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifi, 26);
    lv_obj_set_y(ui_wifi, 0);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SD = lv_img_create(ui_Status_Bar);
    lv_img_set_src(ui_SD, &ui_img_sd_card_png);
    lv_obj_set_width(ui_SD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SD, -70);
    lv_obj_set_y(ui_SD, 0);
    lv_obj_set_align(ui_SD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SD, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Clock = lv_label_create(ui_Status_Bar);
    lv_obj_set_width(ui_Clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clock, 60);
    lv_obj_set_y(ui_Clock, 0);
    lv_obj_set_align(ui_Clock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clock, "12:39");
    lv_obj_set_style_text_font(ui_Clock, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
