// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project_OTR_UI

#include "../ui.h"

void ui_Startup_screen_init(void)
{
    ui_Startup = lv_obj_create(NULL);
    lv_obj_add_state(ui_Startup, LV_STATE_CHECKED | LV_STATE_PRESSED | LV_STATE_FOCUSED);       /// States
    lv_obj_clear_flag(ui_Startup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Startup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Startup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Startup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_Startup, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_width(ui_Startup, 5, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_opensourcehardwarelogo = lv_img_create(ui_Startup);
    lv_img_set_src(ui_opensourcehardwarelogo, &ui_img_opensourcehardware150x150_png);
    lv_obj_set_width(ui_opensourcehardwarelogo, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_opensourcehardwarelogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_opensourcehardwarelogo, 0);
    lv_obj_set_y(ui_opensourcehardwarelogo, 50);
    lv_obj_set_align(ui_opensourcehardwarelogo, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_opensourcehardwarelogo, LV_STATE_FOCUSED);       /// States
    lv_obj_add_flag(ui_opensourcehardwarelogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_opensourcehardwarelogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_opensourcehardwarelogo, 128);

    ui_otrLogo = lv_img_create(ui_Startup);
    lv_img_set_src(ui_otrLogo, &ui_img_logo160x160_png);
    lv_obj_set_width(ui_otrLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_otrLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_otrLogo, 0);
    lv_obj_set_y(ui_otrLogo, -75);
    lv_obj_set_align(ui_otrLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_otrLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_otrLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Startup);
    lv_obj_set_width(ui_Button1, 120);
    lv_obj_set_height(ui_Button1, 60);
    lv_obj_set_x(ui_Button1, 1);
    lv_obj_set_y(ui_Button1, 128);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "EID TAG \nREADER");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_Label1, 2, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_Label1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
