// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UIBACKUP

#ifndef _OTR_AMOLED_UIBACKUP_UI_H
#define _OTR_AMOLED_UIBACKUP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
void ui_event_Main_ButtonNewSession(lv_event_t * e);
extern lv_obj_t * ui_Main_ButtonNewSession;
extern lv_obj_t * ui_Main_Label2;
extern lv_obj_t * ui_Main_TopPanel;
extern lv_obj_t * ui_Main_TopPanelBattery;
void ui_event_Main_TopPanelScan(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelScan;
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelButtonSettings;
void ui_event_Main_TopPanelButtonTime(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelButtonTime;
extern lv_obj_t * ui_Main_TopPanelTime;
extern lv_obj_t * ui_Main_Label1;
void ui_event_Main_ButtonRecentSession(lv_event_t * e);
extern lv_obj_t * ui_Main_ButtonRecentSession;
extern lv_obj_t * ui_Main_Label4;
extern lv_obj_t * ui_Main_RollerRecentSessions;
// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Main_Label3;
extern lv_obj_t * ui_Time_Label_Date;
extern lv_obj_t * ui_Time_Label_Time;
void ui_event_Time_SetTime(lv_event_t * e);
extern lv_obj_t * ui_Time_SetTime;
extern lv_obj_t * ui_Time_Label4;
void ui_event_Time_Sync(lv_event_t * e);
extern lv_obj_t * ui_Time_Sync;
extern lv_obj_t * ui_Time_Label1;
// SCREEN: ui_SetTime
void ui_SetTime_screen_init(void);
void ui_event_SetTime(lv_event_t * e);
extern lv_obj_t * ui_SetTime;
void ui_event_SetTime_TabView(lv_event_t * e);
extern lv_obj_t * ui_SetTime_TabView;
extern lv_obj_t * ui_SetTime_TabPageTime;
extern lv_obj_t * ui_Time_RollerHour;
extern lv_obj_t * ui_Time_RollerMinute;
extern lv_obj_t * ui_Time_RollerAMPM;
void ui_event_SetTime_ButtonManual(lv_event_t * e);
extern lv_obj_t * ui_SetTime_ButtonManual;
extern lv_obj_t * ui_SetTime_Label5;
extern lv_obj_t * ui_SetTime_TabPageDate;
extern lv_obj_t * ui_Date_RollerDay;
extern lv_obj_t * ui_Date_RollerMonth;
extern lv_obj_t * ui_Date_RollerYear;
void ui_event_SetTime_ButtonManualDate(lv_event_t * e);
extern lv_obj_t * ui_SetTime_ButtonManualDate;
extern lv_obj_t * ui_SetTime_Label2;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Settings_TabView;
extern lv_obj_t * ui_Settings_TabPageScan;
extern lv_obj_t * ui_Settings_SwitchScan;
void ui_event_Settings_CheckboxWL134A(lv_event_t * e);
extern lv_obj_t * ui_Settings_CheckboxWL134A;
void ui_event_Settings_CheckboxP1Design(lv_event_t * e);
extern lv_obj_t * ui_Settings_CheckboxP1Design;
extern lv_obj_t * ui_Settings_LabelScanResult;
extern lv_obj_t * ui_Settings_TabPageAP;
extern lv_obj_t * ui_Settings_SwitchAP;
extern lv_obj_t * ui_Settings_SwitchWifi;
extern lv_obj_t * ui_Settings_SwitchBlueTooth;
extern lv_obj_t * ui_Settings_ImgButton1;
// SCREEN: ui_Scan
void ui_Scan_screen_init(void);
extern lv_obj_t * ui_Scan;
extern lv_obj_t * ui_Scan_TabView;
extern lv_obj_t * ui_Scan_TabScan;
extern lv_obj_t * ui_Scan_LabelInfo;
extern lv_obj_t * ui_Scan_LabelTagID;
extern lv_obj_t * ui_Scan_Label5;
extern lv_obj_t * ui_Scan_DropdownMode;
extern lv_obj_t * ui_Scan_Gender;
extern lv_obj_t * ui_Scan_Age;
extern lv_obj_t * ui_Scan_DropdownStatus;
extern lv_obj_t * ui_Scan_Button;
extern lv_obj_t * ui_Scan_ButtonLabel;
extern lv_obj_t * ui_Scan_TabDetails;
extern lv_obj_t * ui_Scan_TabView2;
extern lv_obj_t * ui_Scan_TabDetails;
extern lv_obj_t * ui_Scan_LabelNmae;
extern lv_obj_t * ui_Scan_LabelVisualID;
extern lv_obj_t * ui_Scan_DropdownLocation;
extern lv_obj_t * ui_Scan_DropdownGroup;
extern lv_obj_t * ui_Scan_Comments;
extern lv_obj_t * ui_Scan_TabTreat;
extern lv_obj_t * ui_Scan_Treatment;
extern lv_obj_t * ui_Scan_Product;
extern lv_obj_t * ui_Scan_Dose;
extern lv_obj_t * ui_Scan_Human;
extern lv_obj_t * ui_Scan_TabTrait;
extern lv_obj_t * ui_Scan_TopPanel;
extern lv_obj_t * ui_Scan_TopPanelBattery;
void ui_event_Scan_TopPanelScan(lv_event_t * e);
extern lv_obj_t * ui_Scan_TopPanelScan;
void ui_event_Scan_TopPanelButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_Scan_TopPanelButtonSettings;
void ui_event_Scan_TopPanelButtonTime(lv_event_t * e);
extern lv_obj_t * ui_Scan_TopPanelButtonTime;
extern lv_obj_t * ui_Scan_TopPanelTime;
// SCREEN: ui_Records
void ui_Records_screen_init(void);
extern lv_obj_t * ui_Records;
// SCREEN: ui_New
void ui_New_screen_init(void);
extern lv_obj_t * ui_New;
extern lv_obj_t * ui_New_RFID;
extern lv_obj_t * ui_New_DropdownBreed;
extern lv_obj_t * ui_New_DropdownType;
extern lv_obj_t * ui_New_DropdownLocation;
extern lv_obj_t * ui_New_DropdownGroup;
extern lv_obj_t * ui_New_SwitchGender;
extern lv_obj_t * ui_New_LabelGender;
extern lv_obj_t * ui_New_LabelGender1;
extern lv_obj_t * ui_New_LabelGender2;
extern lv_obj_t * ui_New_ButtonAdd;
extern lv_obj_t * ui_New_Label4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_battery_3_bar_png);    // assets/battery_3_bar.png
LV_IMG_DECLARE(ui_img_contactless_png);    // assets/contactless.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_contactless_off_png);    // assets/contactless_off.png
LV_IMG_DECLARE(ui_img_wifi_tethering_off_png);    // assets/wifi_tethering_off.png
LV_IMG_DECLARE(ui_img_wifi_tethering_png);    // assets/wifi_tethering.png
LV_IMG_DECLARE(ui_img_wifi_off_png);    // assets/wifi_off.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_bluetooth_disabled_png);    // assets/bluetooth_disabled.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_volume_up_png);    // assets/volume_up.png
LV_IMG_DECLARE(ui_img_add_circle_png);    // assets/add_circle.png
LV_IMG_DECLARE(ui_img_arrow_back_png);    // assets/arrow_back.png
LV_IMG_DECLARE(ui_img_battery_1_bar_png);    // assets/battery_1_bar.png
LV_IMG_DECLARE(ui_img_battery_2_bar_png);    // assets/battery_2_bar.png
LV_IMG_DECLARE(ui_img_battery_4_bar_png);    // assets/battery_4_bar.png
LV_IMG_DECLARE(ui_img_battery_5_bar_png);    // assets/battery_5_bar.png
LV_IMG_DECLARE(ui_img_battery_alert_png);    // assets/battery_alert.png
LV_IMG_DECLARE(ui_img_battery_charging_full_png);    // assets/battery_charging_full.png
LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/battery_full.png
LV_IMG_DECLARE(ui_img_cancel_png);    // assets/cancel.png
LV_IMG_DECLARE(ui_img_sd_card_png);    // assets/sd_card.png
LV_IMG_DECLARE(ui_img_volume_down_png);    // assets/volume_down.png
LV_IMG_DECLARE(ui_img_volume_off_png);    // assets/volume_off.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
