// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UIBACKUP

#include "../ui.h"

void ui_New_screen_init(void)
{
    ui_New = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_New, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_New_RFID = lv_label_create(ui_New);
    lv_obj_set_width(ui_New_RFID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_New_RFID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_RFID, lv_pct(0));
    lv_obj_set_y(ui_New_RFID, lv_pct(-45));
    lv_obj_set_align(ui_New_RFID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_New_RFID, "###_############");
    lv_obj_set_style_text_font(ui_New_RFID, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_DropdownBreed = lv_dropdown_create(ui_New);
    lv_dropdown_set_options(ui_New_DropdownBreed, "Aus White\nDorper\nCrossbred");
    lv_obj_set_width(ui_New_DropdownBreed, lv_pct(95));
    lv_obj_set_height(ui_New_DropdownBreed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_DropdownBreed, lv_pct(0));
    lv_obj_set_y(ui_New_DropdownBreed, lv_pct(-10));
    lv_obj_set_align(ui_New_DropdownBreed, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_New_DropdownBreed, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_New_DropdownBreed, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_New_DropdownBreed, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_New_DropdownBreed), &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_DropdownType = lv_dropdown_create(ui_New);
    lv_dropdown_set_options(ui_New_DropdownType, "Commercial\nStud");
    lv_obj_set_width(ui_New_DropdownType, lv_pct(95));
    lv_obj_set_height(ui_New_DropdownType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_New_DropdownType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_New_DropdownType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_New_DropdownType, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_New_DropdownType, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_New_DropdownType), &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_DropdownLocation = lv_dropdown_create(ui_New);
    lv_dropdown_set_options(ui_New_DropdownLocation, "Dorethea\nBellevue");
    lv_obj_set_width(ui_New_DropdownLocation, lv_pct(95));
    lv_obj_set_height(ui_New_DropdownLocation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_DropdownLocation, lv_pct(0));
    lv_obj_set_y(ui_New_DropdownLocation, lv_pct(10));
    lv_obj_set_align(ui_New_DropdownLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_New_DropdownLocation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_New_DropdownLocation, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_New_DropdownLocation, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_New_DropdownLocation), &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_DropdownGroup = lv_dropdown_create(ui_New);
    lv_dropdown_set_options(ui_New_DropdownGroup, "Lambs\nEwes\nRams\nMaidens");
    lv_obj_set_width(ui_New_DropdownGroup, lv_pct(95));
    lv_obj_set_height(ui_New_DropdownGroup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_DropdownGroup, lv_pct(0));
    lv_obj_set_y(ui_New_DropdownGroup, lv_pct(20));
    lv_obj_set_align(ui_New_DropdownGroup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_New_DropdownGroup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_New_DropdownGroup, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_New_DropdownGroup, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_New_DropdownGroup), &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_SwitchGender = lv_switch_create(ui_New);
    lv_obj_set_width(ui_New_SwitchGender, lv_pct(55));
    lv_obj_set_height(ui_New_SwitchGender, lv_pct(17));
    lv_obj_set_x(ui_New_SwitchGender, lv_pct(0));
    lv_obj_set_y(ui_New_SwitchGender, lv_pct(-25));
    lv_obj_set_align(ui_New_SwitchGender, LV_ALIGN_CENTER);


    ui_New_LabelGender = lv_label_create(ui_New);
    lv_obj_set_width(ui_New_LabelGender, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_New_LabelGender, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_LabelGender, lv_pct(0));
    lv_obj_set_y(ui_New_LabelGender, lv_pct(-38));
    lv_obj_set_align(ui_New_LabelGender, LV_ALIGN_CENTER);
    lv_label_set_text(ui_New_LabelGender, "Gender");
    lv_obj_set_style_text_font(ui_New_LabelGender, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_LabelGender1 = lv_label_create(ui_New);
    lv_obj_set_width(ui_New_LabelGender1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_New_LabelGender1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_LabelGender1, lv_pct(-38));
    lv_obj_set_y(ui_New_LabelGender1, lv_pct(-25));
    lv_obj_set_align(ui_New_LabelGender1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_New_LabelGender1, "M");
    lv_obj_set_style_text_font(ui_New_LabelGender1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_LabelGender2 = lv_label_create(ui_New);
    lv_obj_set_width(ui_New_LabelGender2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_New_LabelGender2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_New_LabelGender2, lv_pct(38));
    lv_obj_set_y(ui_New_LabelGender2, lv_pct(-25));
    lv_obj_set_align(ui_New_LabelGender2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_New_LabelGender2, "F");
    lv_obj_set_style_text_font(ui_New_LabelGender2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_New_ButtonAdd = lv_btn_create(ui_New);
    lv_obj_set_width(ui_New_ButtonAdd, lv_pct(90));
    lv_obj_set_height(ui_New_ButtonAdd, lv_pct(20));
    lv_obj_set_x(ui_New_ButtonAdd, lv_pct(0));
    lv_obj_set_y(ui_New_ButtonAdd, lv_pct(38));
    lv_obj_set_align(ui_New_ButtonAdd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_New_ButtonAdd, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_New_ButtonAdd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_New_Label4 = lv_label_create(ui_New_ButtonAdd);
    lv_obj_set_width(ui_New_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_New_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_New_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_New_Label4, "ADD");
    lv_obj_set_style_text_font(ui_New_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}
