// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UIBACKUP

#include "../ui.h"

void ui_Records_screen_init(void)
{
    ui_Records = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Records, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
