// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UI

#include "../ui.h"

void ui_Scan_screen_init(void)
{
    ui_Scan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Scan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scan_TabView = lv_tabview_create(ui_Scan, LV_DIR_BOTTOM, 100);
    lv_obj_set_width(ui_Scan_TabView, lv_pct(100));
    lv_obj_set_height(ui_Scan_TabView, lv_pct(100));
    lv_obj_set_align(ui_Scan_TabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scan_TabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Scan_TabView, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Scan_TabScan = lv_tabview_add_tab(ui_Scan_TabView, "SCAN");

    ui_Scan_LabelMain = lv_label_create(ui_Scan_TabScan);
    lv_obj_set_width(ui_Scan_LabelMain, lv_pct(90));
    lv_obj_set_height(ui_Scan_LabelMain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_LabelMain, 0);
    lv_obj_set_y(ui_Scan_LabelMain, lv_pct(20));
    lv_obj_set_align(ui_Scan_LabelMain, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scan_LabelMain, "CHAD 150");
    lv_label_set_recolor(ui_Scan_LabelMain, "true");
    lv_obj_set_style_text_color(ui_Scan_LabelMain, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scan_LabelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Scan_LabelMain, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scan_LabelMain, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Scan_LabelMain, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Scan_LabelMain, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scan_LabelMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_LabelTagID = lv_label_create(ui_Scan_TabScan);
    lv_obj_set_width(ui_Scan_LabelTagID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_LabelTagID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_LabelTagID, lv_pct(0));
    lv_obj_set_y(ui_Scan_LabelTagID, lv_pct(10));
    lv_obj_set_align(ui_Scan_LabelTagID, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Scan_LabelTagID, "###_############");
    lv_obj_set_style_text_font(ui_Scan_LabelTagID, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_LabelNLISID = lv_label_create(ui_Scan_TabScan);
    lv_obj_set_width(ui_Scan_LabelNLISID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_LabelNLISID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_LabelNLISID, lv_pct(0));
    lv_obj_set_y(ui_Scan_LabelNLISID, lv_pct(18));
    lv_obj_set_align(ui_Scan_LabelNLISID, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Scan_LabelNLISID, "################");
    lv_obj_set_style_text_font(ui_Scan_LabelNLISID, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_Label5 = lv_label_create(ui_Scan_TabScan);
    lv_obj_set_width(ui_Scan_Label5, lv_pct(90));
    lv_obj_set_height(ui_Scan_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_Label5, lv_pct(-1));
    lv_obj_set_y(ui_Scan_Label5, lv_pct(-20));
    lv_obj_set_align(ui_Scan_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scan_Label5, "Scan Mode:");
    lv_label_set_recolor(ui_Scan_Label5, "true");
    lv_obj_set_style_text_align(ui_Scan_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scan_Label5, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_LabelList = lv_label_create(ui_Scan_TabScan);
    lv_obj_set_width(ui_Scan_LabelList, lv_pct(100));
    lv_obj_set_height(ui_Scan_LabelList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_LabelList, lv_pct(1));
    lv_obj_set_y(ui_Scan_LabelList, lv_pct(2));
    lv_obj_set_align(ui_Scan_LabelList, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Scan_LabelList, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Scan_LabelList, "Group:");
    lv_obj_set_style_text_font(ui_Scan_LabelList, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_Dropdown2 = lv_dropdown_create(ui_Scan_TabScan);
    lv_dropdown_set_options(ui_Scan_Dropdown2, "Simple\nCount\nFind");
    lv_obj_set_width(ui_Scan_Dropdown2, lv_pct(100));
    lv_obj_set_height(ui_Scan_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_Dropdown2, lv_pct(1));
    lv_obj_set_y(ui_Scan_Dropdown2, lv_pct(-8));
    lv_obj_set_align(ui_Scan_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scan_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_Scan_TopPanel = lv_obj_create(ui_Scan_TabScan);
    lv_obj_set_width(ui_Scan_TopPanel, lv_pct(108));
    lv_obj_set_height(ui_Scan_TopPanel, lv_pct(12));
    lv_obj_set_x(ui_Scan_TopPanel, lv_pct(0));
    lv_obj_set_y(ui_Scan_TopPanel, lv_pct(-47));
    lv_obj_set_align(ui_Scan_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scan_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scan_TopPanelBattery = lv_img_create(ui_Scan_TopPanel);
    lv_img_set_src(ui_Scan_TopPanelBattery, &ui_img_battery_3_bar_png);
    lv_obj_set_width(ui_Scan_TopPanelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_TopPanelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_TopPanelBattery, lv_pct(5));
    lv_obj_set_y(ui_Scan_TopPanelBattery, lv_pct(0));
    lv_obj_set_align(ui_Scan_TopPanelBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scan_TopPanelBattery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Scan_TopPanelBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scan_TopPanelScan = lv_img_create(ui_Scan_TopPanel);
    lv_img_set_src(ui_Scan_TopPanelScan, &ui_img_contactless_png);
    lv_obj_set_width(ui_Scan_TopPanelScan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_TopPanelScan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_TopPanelScan, lv_pct(-45));
    lv_obj_set_y(ui_Scan_TopPanelScan, lv_pct(0));
    lv_obj_set_align(ui_Scan_TopPanelScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scan_TopPanelScan, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Scan_TopPanelScan,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Scan_TopPanelButtonSettings = lv_imgbtn_create(ui_Scan_TopPanel);
    lv_imgbtn_set_src(ui_Scan_TopPanelButtonSettings, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings_png, NULL);
    lv_imgbtn_set_src(ui_Scan_TopPanelButtonSettings, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_settings_png, NULL);
    lv_obj_set_height(ui_Scan_TopPanelButtonSettings, 48);
    lv_obj_set_width(ui_Scan_TopPanelButtonSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Scan_TopPanelButtonSettings, lv_pct(-20));
    lv_obj_set_y(ui_Scan_TopPanelButtonSettings, lv_pct(0));
    lv_obj_set_align(ui_Scan_TopPanelButtonSettings, LV_ALIGN_CENTER);

    ui_Main_TopPanelButtonTime3 = lv_btn_create(ui_Scan_TopPanel);
    lv_obj_set_height(ui_Main_TopPanelButtonTime3, 48);
    lv_obj_set_width(ui_Main_TopPanelButtonTime3, lv_pct(40));
    lv_obj_set_x(ui_Main_TopPanelButtonTime3, lv_pct(35));
    lv_obj_set_y(ui_Main_TopPanelButtonTime3, lv_pct(0));
    lv_obj_set_align(ui_Main_TopPanelButtonTime3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Main_TopPanelButtonTime3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Main_TopPanelButtonTime3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_TopPanelButtonTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_TopPanelButtonTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Main_TopPanelButtonTime3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Main_TopPanelButtonTime3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_TopPanelTime = lv_label_create(ui_Main_TopPanelButtonTime3);
    lv_obj_set_width(ui_Scan_TopPanelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_TopPanelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Scan_TopPanelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scan_TopPanelTime, "22:59");
    lv_obj_set_style_text_color(ui_Scan_TopPanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scan_TopPanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scan_TopPanelTime, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_TabDetails = lv_tabview_add_tab(ui_Scan_TabView, "DETAILS");

    ui_Scan_Label2 = lv_label_create(ui_Scan_TabDetails);
    lv_obj_set_width(ui_Scan_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_Label2, 0);
    lv_obj_set_y(ui_Scan_Label2, lv_pct(-45));
    lv_obj_set_align(ui_Scan_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scan_Label2, "CHAD 001");
    lv_label_set_recolor(ui_Scan_Label2, "true");
    lv_obj_set_style_text_font(ui_Scan_Label2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Scan_Label2, lv_color_hex(0x807D7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scan_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_DropdownLocation = lv_dropdown_create(ui_Scan_TabDetails);
    lv_dropdown_set_options(ui_Scan_DropdownLocation, "Dorethea\nBellevue");
    lv_obj_set_width(ui_Scan_DropdownLocation, lv_pct(100));
    lv_obj_set_height(ui_Scan_DropdownLocation, lv_pct(11));
    lv_obj_set_x(ui_Scan_DropdownLocation, lv_pct(0));
    lv_obj_set_y(ui_Scan_DropdownLocation, lv_pct(-13));
    lv_obj_set_align(ui_Scan_DropdownLocation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scan_DropdownLocation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Scan_DropdownLocation, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Scan_DropdownLocation), &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_DropdownGroup = lv_dropdown_create(ui_Scan_TabDetails);
    lv_dropdown_set_options(ui_Scan_DropdownGroup, "Ewes\nMaidens\nLambs\nRams");
    lv_obj_set_width(ui_Scan_DropdownGroup, lv_pct(100));
    lv_obj_set_height(ui_Scan_DropdownGroup, lv_pct(11));
    lv_obj_set_x(ui_Scan_DropdownGroup, lv_pct(0));
    lv_obj_set_y(ui_Scan_DropdownGroup, lv_pct(-1));
    lv_obj_set_align(ui_Scan_DropdownGroup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Scan_DropdownGroup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Scan_DropdownGroup, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Scan_DropdownGroup), &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_LabelNmae = lv_label_create(ui_Scan_TabDetails);
    lv_obj_set_width(ui_Scan_LabelNmae, lv_pct(100));
    lv_obj_set_height(ui_Scan_LabelNmae, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_LabelNmae, lv_pct(0));
    lv_obj_set_y(ui_Scan_LabelNmae, lv_pct(-33));
    lv_obj_set_align(ui_Scan_LabelNmae, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scan_LabelNmae, "Ronaldo");
    lv_obj_set_style_text_align(ui_Scan_LabelNmae, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scan_LabelNmae, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Scan_TopPanelScan, ui_event_Scan_TopPanelScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scan_TopPanelButtonSettings, ui_event_Scan_TopPanelButtonSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main_TopPanelButtonTime3, ui_event_Main_TopPanelButtonTime3, LV_EVENT_ALL, NULL);

}
