// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UI

#include "../ui.h"

void ui_SetDate_screen_init(void)
{
    ui_SetDate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetDate_ButtonManual = lv_btn_create(ui_SetDate);
    lv_obj_set_width(ui_SetDate_ButtonManual, lv_pct(70));
    lv_obj_set_height(ui_SetDate_ButtonManual, lv_pct(15));
    lv_obj_set_x(ui_SetDate_ButtonManual, lv_pct(0));
    lv_obj_set_y(ui_SetDate_ButtonManual, lv_pct(35));
    lv_obj_set_align(ui_SetDate_ButtonManual, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetDate_ButtonManual, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetDate_ButtonManual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetTime_Label2 = lv_label_create(ui_SetDate_ButtonManual);
    lv_obj_set_width(ui_SetTime_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTime_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SetTime_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTime_Label2, "SET");
    lv_obj_set_style_text_font(ui_SetTime_Label2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTime_Button2 = lv_btn_create(ui_SetDate);
    lv_obj_set_width(ui_SetTime_Button2, 75);
    lv_obj_set_height(ui_SetTime_Button2, 75);
    lv_obj_set_x(ui_SetTime_Button2, 73);
    lv_obj_set_y(ui_SetTime_Button2, -216);
    lv_obj_set_align(ui_SetTime_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTime_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetTime_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SetTime_Button2, &ui_img_arrow_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_SetTime_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_SetTime_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date_RollerDay = lv_roller_create(ui_SetDate);
    lv_roller_set_options(ui_Date_RollerDay,
                          "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Date_RollerDay, lv_pct(33));
    lv_obj_set_height(ui_Date_RollerDay, lv_pct(50));
    lv_obj_set_x(ui_Date_RollerDay, lv_pct(-34));
    lv_obj_set_y(ui_Date_RollerDay, lv_pct(0));
    lv_obj_set_align(ui_Date_RollerDay, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Date_RollerDay, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Date_RollerDay, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Date_RollerMonth = lv_roller_create(ui_SetDate);
    lv_roller_set_options(ui_Date_RollerMonth, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Date_RollerMonth, lv_pct(33));
    lv_obj_set_height(ui_Date_RollerMonth, lv_pct(50));
    lv_obj_set_align(ui_Date_RollerMonth, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Date_RollerMonth, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Date_RollerMonth, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Date_RollerYear = lv_roller_create(ui_SetDate);
    lv_roller_set_options(ui_Date_RollerYear, "24\n25\n26\n27\n28\n29\n30", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Date_RollerYear, lv_pct(33));
    lv_obj_set_height(ui_Date_RollerYear, lv_pct(50));
    lv_obj_set_x(ui_Date_RollerYear, lv_pct(34));
    lv_obj_set_y(ui_Date_RollerYear, lv_pct(0));
    lv_obj_set_align(ui_Date_RollerYear, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_Date_RollerYear, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Date_RollerYear, &lv_font_montserrat_40, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SetDate_ButtonManual, ui_event_SetDate_ButtonManual, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetTime_Button2, ui_event_SetTime_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetDate, ui_event_SetDate, LV_EVENT_ALL, NULL);

}
