// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
lv_obj_t * ui_Main;
lv_obj_t * ui_Main_Label1;
void ui_event_Main_Button1(lv_event_t * e);
lv_obj_t * ui_Main_Button1;
lv_obj_t * ui_Main_Label2;
lv_obj_t * ui_Main_TopPanel;
lv_obj_t * ui_Main_TopPanelBattery;
lv_obj_t * ui_Main_TopPanelScan;
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e);
lv_obj_t * ui_Main_TopPanelButtonSettings;
void ui_event_Main_TopPanelButtonTime(lv_event_t * e);
lv_obj_t * ui_Main_TopPanelButtonTime;
lv_obj_t * ui_Main_TopPanelTime;
lv_obj_t * ui_Main_ImgButton2;


// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
lv_obj_t * ui_Time;
lv_obj_t * ui_Main_Label3;
lv_obj_t * ui_Time_Label_Date;
lv_obj_t * ui_Time_Label_Time;
lv_obj_t * ui_Time_Label_Date2;
void ui_event_Time_SetTime(lv_event_t * e);
lv_obj_t * ui_Time_SetTime;
lv_obj_t * ui_Time_Label4;
void ui_event_Time_SetDate(lv_event_t * e);
lv_obj_t * ui_Time_SetDate;
lv_obj_t * ui_Time_Label1;


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_SettingsTopPanel;
lv_obj_t * ui_SettingsTopPanelBattery;
void ui_event_SettingsTopPanelButtonTime(lv_event_t * e);
lv_obj_t * ui_SettingsTopPanelButtonTime;
lv_obj_t * ui_SettingsTopPanelTime;
lv_obj_t * ui_Settings_Switch1;
lv_obj_t * ui_Settings_Switch2;
lv_obj_t * ui_Settings_Switch3;
lv_obj_t * ui_Settings_Switch4;


// SCREEN: ui_SetTime
void ui_SetTime_screen_init(void);
void ui_event_SetTime(lv_event_t * e);
lv_obj_t * ui_SetTime;
lv_obj_t * ui_Time_RollerHour;
lv_obj_t * ui_Time_RollerMinute;
lv_obj_t * ui_Time_RollerAMPM;
void ui_event_SetTime_ButtonManual(lv_event_t * e);
lv_obj_t * ui_SetTime_ButtonManual;
lv_obj_t * ui_SetTime_Label5;
void ui_event_SetTime_Button5(lv_event_t * e);
lv_obj_t * ui_SetTime_Button5;


// SCREEN: ui_SetDate
void ui_SetDate_screen_init(void);
void ui_event_SetDate(lv_event_t * e);
lv_obj_t * ui_SetDate;
void ui_event_SetDate_ButtonManual(lv_event_t * e);
lv_obj_t * ui_SetDate_ButtonManual;
lv_obj_t * ui_SetTime_Label2;
void ui_event_SetTime_Button2(lv_event_t * e);
lv_obj_t * ui_SetTime_Button2;
lv_obj_t * ui_Date_RollerDay;
lv_obj_t * ui_Date_RollerMonth;
lv_obj_t * ui_Date_RollerYear;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Time_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        UI_MAIN_SCREEN_LOAD(e);
    }
}
void ui_event_Main_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        btn_event_cb(e);
    }
}
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_Main_TopPanelButtonTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Main_screen_init);
    }
}
void ui_event_Time_SetTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetTime, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SetTime_screen_init);
    }
}
void ui_event_Time_SetDate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetDate, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SetDate_screen_init);
    }
}
void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Time_screen_init);
    }
}
void ui_event_SettingsTopPanelButtonTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_SetTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_roller_set_property(ui_Time_RollerHour, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 11);
        _ui_roller_set_property(ui_Time_RollerMinute, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 30);
        _ui_roller_set_property(ui_Time_RollerAMPM, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 0);
    }
}
void ui_event_SetTime_ButtonManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setTimeManual(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_SetTime_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_SetDate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_roller_set_property(ui_Date_RollerDay, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 18);
        _ui_roller_set_property(ui_Date_RollerMonth, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 3);
    }
}
void ui_event_SetDate_ButtonManual(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        setDateManual(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}
void ui_event_SetTime_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Time, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Time_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_screen_init();
    ui_Time_screen_init();
    ui_Settings_screen_init();
    ui_SetTime_screen_init();
    ui_SetDate_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main);
}
