// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UI

#ifndef _OTR_AMOLED_UI_UI_H
#define _OTR_AMOLED_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Main_Label1;
void ui_event_Main_Button1(lv_event_t * e);
extern lv_obj_t * ui_Main_Button1;
extern lv_obj_t * ui_Main_Label2;
extern lv_obj_t * ui_Main_TopPanel;
extern lv_obj_t * ui_Main_TopPanelBattery;
extern lv_obj_t * ui_Main_TopPanelScan;
void ui_event_Main_TopPanelButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelButtonSettings;
void ui_event_Main_TopPanelButtonTime(lv_event_t * e);
extern lv_obj_t * ui_Main_TopPanelButtonTime;
extern lv_obj_t * ui_Main_TopPanelTime;
extern lv_obj_t * ui_Main_ImgButton2;
// SCREEN: ui_Time
void ui_Time_screen_init(void);
void ui_event_Time(lv_event_t * e);
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Main_Label3;
extern lv_obj_t * ui_Time_Label_Date;
extern lv_obj_t * ui_Time_Label_Time;
extern lv_obj_t * ui_Time_Label_Date2;
extern lv_obj_t * ui_Time_Keyboard1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_battery_full_png);    // assets/battery_full.png
LV_IMG_DECLARE(ui_img_contactless_png);    // assets/contactless.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_contactless_off_png);    // assets/contactless_off.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
