// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: OTR_AMOLED_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void UI_MAIN_SCREEN_LOAD(lv_event_t * e);
void btn_event_cb(lv_event_t * e);
void scanSwitched(lv_event_t * e);
void setTimeManual(lv_event_t * e);
void setDateManual(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
