// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project_OTR_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Startup
void ui_Startup_screen_init(void);
lv_obj_t * ui_Startup;
lv_obj_t * ui_opensourcehardwarelogo;
lv_obj_t * ui_otrLogo;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
lv_obj_t * ui_Status_Bar;
lv_obj_t * ui_RFID;
lv_obj_t * ui_Battery;
lv_obj_t * ui_wifiAP;
lv_obj_t * ui_wifi;
lv_obj_t * ui_SD;
lv_obj_t * ui_Clock;
lv_obj_t * ui_Main_Panel;
lv_obj_t * ui_Main_Scan;
lv_obj_t * ui_Main_Label3;
lv_obj_t * ui_Main_Records;
lv_obj_t * ui_Main_Label1;
lv_obj_t * ui_Main_Setup;
lv_obj_t * ui_Main_Label2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_battery_charging_[1] = {&ui_img_battery_charging_20_png};
const lv_img_dsc_t * ui_imgset_logox[1] = {&ui_img_logo160x160_png};
const lv_img_dsc_t * ui_imgset_opensourcehardwarex[1] = {&ui_img_opensourcehardware150x150_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Main_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Startup_screen_init();
    ui_Main_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Startup);
}
