// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project_OTR_UI

#ifndef _SQUARELINE_PROJECT_OTR_UI_UI_H
#define _SQUARELINE_PROJECT_OTR_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void logo_spin_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Startup
void ui_Startup_screen_init(void);
extern lv_obj_t * ui_Startup;
extern lv_obj_t * ui_opensourcehardwarelogo;
extern lv_obj_t * ui_otrLogo;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Status_Bar;
extern lv_obj_t * ui_RFID;
extern lv_obj_t * ui_Bluetooth;
extern lv_obj_t * ui_wifiAP;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_SD;
extern lv_obj_t * ui_Clock;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_opensourcehardware150x150_png);    // assets/opensourcehardware150x150.png
LV_IMG_DECLARE(ui_img_logo160x160_png);    // assets/logo160x160.png
LV_IMG_DECLARE(ui_img_contactless_png);    // assets/contactless.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_wifi_tethering_png);    // assets/wifi_tethering.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_sd_card_png);    // assets/sd_card.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
